### ISSUE TITLE
Use as Node Module?

### ISSUE THREAD

**Issue by mithrayls** [horosgrisa/cli-marked#1]
I would love to integrate this into another project. But I can't do this if it's only made available as a global package. How hard would it be to make this possible?

**Comment by horosgrisa** [comment]
@mithrayls 
See https://github.com/horosgrisa/cli-marked/blob/master/bin/md.js


Example:
```js
const marked = require('marked');
const TerminalRenderer = require('cli-marked');

marked.setOptions({
  renderer: new TerminalRenderer({}),
  mangle: false,
  emoji: true,
  breaks: false,
  gfm: true,
  smartypants: false,
});

console.log(markdown.toString());

```

**Comment by mithrayls** [comment]
Just noticed your reply. Thank you! Did not realize it was this easy!
